baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'AI by Mai'



[params]

  description = "AI by Mai is under construction at the moment."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list
  googleAnalytics = ""