baseURL = "https://www.aibymai.dev/"
languageCode = 'en-us'
title = 'AI by Mai'

[params]
  description = "Welcome to AI by Mai 🏄‍♀️"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  showProjectsList = true # show projects list by default (if projects data file exists).
  showDeepDivesList = true
  
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about'
    weight = 2
  [[menu.main]]
    name = 'Writtings'
    url = '/posts'
    weight = 3
  [[menu.main]]
    name = 'Projects'
    url = '/projects'
    weight = 4
  [[menu.main]]
    name = 'Deep Dives'
    url = '/deep-dives'
    weight = 5
  [[menu.main]]
    name = 'Tags'
    url = '/tags'
    weight = 5


  [[params.social]]
    name = 'github'
    link = 'https://github.com/13Mai13'
  [[params.social]]
    name = 'linkedIn'
    link = 'https://www.linkedin.com/in/maialen-berrondo-43197b94/'

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  deep-dives = "/deep-dives/:filename/"